default: &default
  model: &model-default
    k: 5  # The number of GNN layers
    att_head_num: 2  # number of attention heads of the final graph nodes' pooling
    gnn_dim: 100  # dimension of the GNN layers
    freeze_ent_emb: True  # Whether to freeze the entity embedding layer.
    ie_dim: 200  # number of the hidden units of the MInt operator.
    ie_layer_num: 1  # number of hidden layers in the MInt operator
    cxt_node_connects_all: True  # Whether to connect the interaction node to all the retrieved KG nodes or only the linked nodes.
    encoder_name_or_path: t5-base
    xattn_dim_head: 64
    xattn_heads: 8
    xattn_every: 1
    xattn_ff_mult: 4
  data: &data-default
    kg_only_use_qa_nodes: False
    max_node_num: 200  # Max number of nodes / the threshold used to prune nodes.
    num_dataloader_workers: 8
    mlm_probability: 0.2
    encoder_input: question
    decoder_label: choices
    has_choice_graph: False  # does each choice has a subgraph?
  optim: &optim-default
    # Optimization
    loss: cross_entropy  # model type
    optimizer: adamw  # the optimizer
    batch_size: 256
    max_grad_norm: 1.0  # max grad norm (0 to disable)
    n_epochs: 100  # total number of training epochs to perform.
    eval_batch_size: 64
    init_range: 0.02  # stddev when initializing with normal distribution
    redef_epoch_steps: -1
    # Regularization:
    dropouti: 0.2  # dropout for embedding layer
    dropoutg: 0.2  # dropout for GNN layers
    dropoutf: 0.2  # dropout for fully-connected layers
    # Customized
    fp16: True
    dist_backend: nccl # gloo, nccl or mpi
    batch_size: 128
    learning_rate: 0.0001
    freeze_lm: True
    freeze_non_lm: False
    max_seq_len: 512
    strategy: auto
  misc: &misc-default
    mode: train  # run training or evaluation
    save_dir: ./saved_models/  # model output directory
    save_model: 2  # 0: do not save model checkpoints. 1: save if best dev. 2: save always
    checkpoint_path:  # The checkpoint for finetuning, or to resume training from if restore_training is set
    restore_training: False  # Whether to restore training from the checkpoint
    # added
    wandb_mode: online # online, offline or disabled
    wandb_project: commensense
    world_size: 1
    fast_dev_run: False
    log_interval: 20
    run_name:
    save_interval: 5
    log_dir: logs
    retrieve_text: False
    prefix_ratio: 0.2
    monitor: accuracy
    monitor_mode: max


conceptnet: &conceptnet
  kg: conceptnet
  num_relations: 17
  ent_emb_paths: data/cpnet/tzw.ent.npy


csqa: &csqa
  dataset: csqa
  train_statements: data/csqa/statement/train.statement.jsonl
  train_adj: data/csqa/adj/train
  dev_statements: data/csqa/statement/dev.statement.jsonl
  dev_adj: data/csqa/adj/dev
  legacy_adj: False
  num_choices: 5

csqa_sanity: &csqa-sanity
  dataset: csqa
  train_statements: data/csqa_sanity/statment/train.statement.jsonl
  train_adj: data/csqa_sanity/adj/train
  dev_statements: data/csqa_sanity/statment/train.statement.jsonl
  dev_adj: data/csqa_sanity/adj/train
  num_choices: 5


finetune_csqa: &finetune-csqa
  <<: *default
  data:
    <<: *data-default
    <<: *conceptnet
    <<: *csqa
  optim: &finetune-csqa-optim
    <<: *optim-default
    learning_rate: 0.001
    batch_size: 48
    max_seq_len: 128
    freeze_lm: True
    freeze_non_lm: False
  misc: &finetune-csqa-misc
    <<: *misc-default
    fast_dev_run: False

finetune_csqa_sanity: &finetune-csqa-sanity
  <<: *finetune-csqa
  data:
    <<: *data-default
    <<: *conceptnet
    <<: *csqa-sanity
  optim:
    <<: *optim-default
    learning_rate: 0.005
    batch_size: 64
    max_seq_len: 512
    freeze_lm: True
    freeze_non_lm: False
  misc:
    <<: *misc-default
    fast_dev_run: True
    log_interval: 4

finetune_csqa_pretrained_adapter:
  <<: *finetune-csqa
  misc:
    <<: *misc-default
    checkpoint_path: artifacts/pretrained/lit_obqa_t5b_e20_adapter.ckpt